### PR TITLE
Fix PropTypes warnings, make library compatible with react 16, see issue #57

### PR DESCRIPTION
**Pull request by philipstanislaus**
Fix warnings about accessing PropTypes via the main React package by using prop-types package from npm instead.

Linting and tests run as expected.

### CODE REVIEW

**Comment by philipstanislaus** [comment]
@alexkuz could you please provide feedback on this fix? Thanks!

**Comment by ra100** [comment]
I suppose this is not just about warnings, but should fix compatibility with react@16, as prop-types have been removed from react.

**Comment by philipstanislaus** [comment]
True, I changed the title @ra100

**Comment by alexkuz** [comment]
@philipstanislaus thank you! Sorry it took so long.

**Comment by philipstanislaus** [comment]
@alexkuz thanks! Could you directly publish the changes to npm too?

**Comment by alexkuz** [comment]
@philipstanislaus a bit later, I also have to update all dependencies to get rid of warnings.

**Comment by philipstanislaus** [comment]
@alexkuz alright, thanks!

**Comment by philipstanislaus** [comment]
@alexkuz any update on this? Thanks!

**Comment by alexkuz** [comment]
@philipstanislaus still working on this, sorry :) There was a dependency that required some updates, but I think it's done, just need to check it again.

**Comment by alexkuz** [comment]
Published in v0.7.0. Happy New Year everyone!

**Pull request merged**
