### PR TITLE
Fixes/datepicker issues

### PR DESCRIPTION
**Pull request by alexbeletsky**
- I had to disable perftools, looks like there is a problem with package in react 15.2.1
- Prevent `pattern` to propagate to `inputProps`

### CODE REVIEW

**Comment by alexbeletsky** [comment]
My previous implementation was not totally correct, since instead of dropping `pattern` in `InputPopup` i need to do it in `Mask`.

@alexkuz that would be nice if you review and update package in npm. :)

**Comment by alexkuz** [comment]
Thank you! I'll do for sure, but later.

**Comment by alexkuz** [comment]
@alexbeletsky I published `v0.5.0-beta1` - please check if this is still relevant.

**Comment by alexbeletsky** [comment]
From the [code](https://github.com/alexkuz/react-input-enhancements/blob/master/src/Mask.jsx#L99) I can see, that still problem exists. Pattern will be propagated to `inputsPros`, so I think that issue is still actual. 

At the moment, I'm still sticking to [own fork](https://github.com/blogfoster/react-input-enhancements/commits/master) on input enhancers, that prevents those issues.

**Comment by alexkuz** [comment]
@alexbeletsky sorry, forgot to mention - it's on [next](https://github.com/alexkuz/react-input-enhancements/tree/next) branch for now

**Comment by alexbeletsky** [comment]
@alexkuz ok, that looks like a lot of things changed there :) need to try it.

**Pull request closed without merging**
