### PR TITLE
:beer:

### PR DESCRIPTION
**Pull request by zzz6519003**

### CODE REVIEW

**Comment by alexkuz** [comment]
Please provide some comments why you think this is needed. :beer: doesn't help much.

**Comment by zzz6519003** [comment]
just paste some crap like "adspfadsf" into the input field, then you click
elsewhere, then the content should be cleanned cuz it doesn't match a word.

2015-12-24 16:21 GMT+08:00 Alexander Kuznetsov notifications@github.com:

> Please provide some comments why you think this is needed. [image: :beer:]
> doesn't help much.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alexkuz/react-input-enhancements/pull/2#issuecomment-167066812
> .

## 

yours,

正中赵
about.me/zzz6519003
[image: 正中赵 on about.me]
  http://about.me/zzz6519003

**Comment by alexkuz** [comment]
I'm not sure it should. I see `Autocomplete` as just a hinter, that doesn't require you to use one of the options. And if you need more strict behaviour, it should be easy enough to add a HOC.

**Comment by zzz6519003** [comment]
what't hoc  XD

2015-12-25 15:50 GMT+08:00 Alexander Kuznetsov notifications@github.com:

> I'm not sure it should. I see Autocomplete as just a hinter, that doesn't
> require you to use one of the options. And if you need more strict
> behaviour, it should be easy enough to add a HOC.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alexkuz/react-input-enhancements/pull/2#issuecomment-167205815
> .

## 

yours,

正中赵
about.me/zzz6519003
[image: 正中赵 on about.me]
  http://about.me/zzz6519003

**Comment by alexkuz** [comment]
[Higher-Order Component](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.bum56fb6e)

**Pull request closed without merging**
