### PR TITLE
#14 ReferenceError: window is not defined when using server-side rendering

### PR DESCRIPTION
**Pull request by spatius**

### CODE REVIEW

**Comment by amgohan** [comment]
Hi @alexkuz can you merge this branch, we want to use react-input-enhancements but get error when server rendering

**Comment by alexkuz** [comment]
@amgohan sorry for delay! I'll try it out later today.

**Comment by alexkuz** [comment]
@spatius I have an error in `Autosize` - `sizerEl` is not defined. I believe it's because `componentDidMount` is used now instead of `componentWillMount`. Can you fix that?

**Comment by alexkuz** [comment]
I've added tests for server-side and client-side rendering and fixed in accordingly, so we don't need this pull anymore, I guess. Thanks for this anyway!

**Pull request closed without merging**
