### PR TITLE
IE-11 flexbox bug workaround

### LINKED ISSUE #39: IE10, IE11 ComboBox popup completely overflows
ComboBox has trouble in IE 11 because of [flexbox bug](https://connect.microsoft.com/IE/feedback/details/802625). The `max-height` style gets completely ignored, content of the ComboBox gets stretched and overflow gets ignored. I found only two simple solutions:
1.  [Set the height to specific size](http://stackoverflow.com/a/31816795) 
2. Don't use flexbox

### PR DESCRIPTION
**Pull request by ReadyPlayerNaN**
This fixes #39

### CODE REVIEW

**Comment by ReadyPlayerNaN** [comment]
bump

**Comment by spetex** [comment]
@alexkuz Whats the hold on this pull request?

**Comment by alexkuz** [comment]
Mostly my procrastination, to be honest, sorry :) I want to finish with my update on stylings, then take care of it. Probably this weekend.

**Comment by spetex** [comment]
Great!

**Comment by alexkuz** [comment]
I've added same fix in `v0.5.0`, so I'll just close this one. Thank you!

**Pull request closed without merging**
